---
title: "Time-Series Analysis for Renewable Energies Data"
author: "Skurativska Kateryna, Zolghadr Sharare"
date: "2023-10-24"
output:
  html_document:
    toc: true
    number_sections: true
  pdf_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Our aim is to analyze energy consumption, especially renewable energies and how it changes over the years. We limit our analysis only for EU-area, as it has more information about renewable energies than any other area. Our plan is to try to answer on the following questions:

1.  Renewable Energy Adoption and Growth
    1.  How does it evolve over time?
    2.  Can we forecast the future growth in a specific region?
    3.  What factors influence the growth?
    4.  What are seasonal and annual trends in renewable energy production and how do they impact energy supply and demand?
2.   Electricity price forecasting
    1.  Can we predict electricity prices based on the availability of renewable energy sources?
    2.  How does integration impact price volatility?
3.  Carbon emission reduction
    1.  How does growth of renewable energy sources contribute to a reduction in carbon
    2.  Can we estimate the potential impact of future renewable energy adoption on future carbon emissions?

The analysis will be made general for the EU and for each country separately.

Data we need:

1.  Energy consumption for each country annually and monthly for each type of energy production

2.  Electricity prices for each country during the same period

3.  CO2 emisions for each country
